# Zsh configuration for ICE
#
# Copyright(C) Shiyue He
#
# If the OS distribution only has bash, install zsh with packet manager
#
# Change the default user with
#     chsh -s /bin/zsh <USER_NAME>
# Install zshrc file
#     ln -s /absolute/path/to/zshrc ~/.zshrc
#

# Options. Get help by running
#   run-help zshoptions
setopt nobeep
setopt extended_history         # Record timestamp of command
setopt hist_ignore_dups         # Ignore duplicated commands history list
setopt hist_ignore_space        # Ignore commands that start with space
setopt hist_verify              # Show command with history expansion to user before running it
setopt complete_in_word         # Allow completion from within a word/phrase
setopt prompt_subst             # Make PROMPT works right
# Aliases
alias l='ls --color=always -l'
alias ls='ls --color=always'
alias ...='../..'
alias ....='../../..'
alias .....='../../../..'
alias ......='../../../../..'

# Autoload functions
autoload -U compinit && compinit	# Completion initalization 
autoload -U colors && colors 		# Functions to easily use colors

# ls color
eval `dircolors`

# zsh completion (from manjaro zsh configuration)
# Run 'run-help zshmodules' to get help for zstyle
zstyle ':completion:*' matcher-list 'm:{[:lower:][:upper:]}={[:upper:][:lower:]}' # Case insensitive tab completion
zstyle ':completion:*' matcher-list 'r:|=*' 'l:|=* r:|=*'   # Coomplete partial words
zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}"         # Colored completion (different colors for dirs/files/etc)

# History file
HISTFILE=~/.zhistory
HISTSIZE=20000
SAVEHIST=20000

# Plugins
local zsh_plugins=~/.zsh/plugins

[[ -e ${zsh_plugins}/zsh-autosuggestions/zsh-autosuggestions.zsh ]] && \
	source ${zsh_plugins}/zsh-autosuggestions/zsh-autosuggestions.zsh

[[ -e ${zsh_plugins}/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh ]] && \
	source ${zsh_plugins}/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# agnoster requires powerline-fonts: sudo apt install fonts-powerline
if [[ -e ${zsh_plugins}/agnoster-zsh-theme/agnoster.zsh-theme ]]; then 
	source ${zsh_plugins}/agnoster-zsh-theme/agnoster.zsh-theme
    
    # Remove segment 2. Default segments are :
    #     1	prompt_status
    #     2	prompt_context
    #     3	prompt_virtualenv
    #     4	prompt_dir
    #     5	prompt_git
    #     6	prompt_end
    AGNOSTER_PROMPT_SEGMENTS[2]=
fi
