"
" Default gvim run command file
" Author: OctHe
" Copyright (C): 2025
"
" =====================================================================

try
  colorscheme seoul256
catch
  colorscheme peachpuff
endtry

" vim: set sw=4 sts=4 et fdm=marker:
