" Simple and lighweight vim run command file. It only contains one file.
" Author: OctHe
" Copyright (C)
" 
" =====================================================================
" Use Vim settings, rather than Vi settings (much better!).
" This must be first, because it changes other options as a side effect.
if &compatible
  set nocompatible
endif

" Enable file type detection.
filetype plugin on
" Enable automatic indentation.
filetype indent on

set runtimepath-=~/.vim
set runtimepath-=~/.vim/after
set runtimepath^=~/.config/slim
set runtimepath+=~/.config/slim/after
set packpath-=~/.vim
set packpath-=~/.vim/after
set packpath^=~/.config/slim
set packpath+=~/.config/slim/after

" Use <Space> as the <Leader>
" This command must be before all keymappings and plugin configs
let mapleader = ' '

" It changes the behavior of star to not jump to next word
" Yank the word into the register s, and then assign it in to the yank
" register (The register / is not writeable directly)
nmap <silent> * "syiw:let @/ = @s<CR>
" Easy-nohlsearch
nnoremap <silent> <Esc> :nohlsearch<CR>
tnoremap <silent> <Esc><Esc> <C-\><C-n><CR>
" Easy indent
vmap < <gv
vmap > >gv
" Show mappings
nnoremap <silent> <Leader>m :verbose map


" Try to install minpac
let s:minpac_dir = expand('~/.config/slim/pack/minpac/opt/minpac')
if !(s:minpac_dir->isdirectory())
  execute '!git clone --depth=1 https://github.com/k-takata/minpac.git' s:minpac_dir
  packadd minpac
endif

function! PackInit() abort
  packadd minpac

  call minpac#init()
  call minpac#add('k-takata/minpac', {'type': 'opt'})

  " Additional plugins here.

  call minpac#add('tpope/vim-sensible')
  call minpac#add('tpope/vim-surround')
  call minpac#add('tpope/vim-vinegar')
  call minpac#add('tpope/vim-commentary')
  call minpac#add('tpope/vim-repeat')
  call minpac#add('tpope/vim-endwise')
  call minpac#add('tpope/vim-dispatch')
  call minpac#add('tpope/vim-fugitive')

call minpac#add('ctrlpvim/ctrlp.vim')

endfunction

" Define user commands for updating/cleaning the plugins.
" Each of them calls PackInit() to load minpac and register
" the information of plugins, then performs the task.
command! PackUpdate call PackInit() | call minpac#update()
command! PackClean  call PackInit() | call minpac#clean()
command! PackStatus packadd minpac | call minpac#init() | call minpac#status()

" Builtin colorschemes: desert, peachpuff, quiet, slate
colorscheme desert

" vim: set sw=2 sts=2 et fdm=marker:
