" 
" Vim run command that clean the runtimepath with dein.vim
" Author: OctHe
" Copyright (C): 2025
" 
" =====================================================================
" Use Vim settings, rather than Vi settings (much better!).
" This must be first, because it changes other options as a side effect.
if &compatible
    set nocompatible
endif

" Enable file type detection.
filetype plugin on
" Enable automatic indentation.
filetype indent on

" source $VIMRUNTIME/vimrc_example.vim

" Keymappings {{{1

" Use <Space> as the <Leader>
" This command must be before all keymappings and plugin configs
let mapleader = ' '

" Easy-nohlsearch
nnoremap <silent> <Esc> :nohlsearch<CR>
tnoremap <silent> <Esc><Esc> <C-\><C-n><CR>

" }}}1

let $CACHE = expand('~/.cache')
if !($CACHE->isdirectory())
    call mkdir($CACHE, 'p')
endif
if &runtimepath !~# '/dein.vim'
    let s:dein_src = $CACHE .. '/dein/repos/github.com/Shougo/dein.vim'
    if !(s:dein_src->isdirectory())
        execute '!git clone https://github.com/Shougo/dein.vim' s:dein_src
    endif
    execute 'set runtimepath^=' .. s:dein_src
endif

" Call dein initialization (required)
call dein#begin($CACHE .. '/dein')

call dein#add('LunarWatcher/auto-pairs')
call dein#add('machakann/vim-sandwich')
call dein#add('tpope/vim-repeat')
call dein#add('tpope/vim-endwise')

if has('python3')
    call dein#add('Shougo/defx.nvim')
else
    call dein#add('tpope/vim-vinegar')
endif

call dein#add('preservim/vim-indent-guides')

call dein#add('justinmk/vim-sneak')
call dein#add('AndrewRadev/splitjoin.vim')

call dein#add('preservim/nerdcommenter')

call dein#add('liuchengxu/vista.vim')
call dein#add('neomake/neomake')

call dein#add('vim-scripts/star-search')
if  has('python3') && executable('/bin/gcc')
    call dein#add('Yggdroot/LeaderF', { 'build': ':LeaderfInstallCExtension' })

    " Snippets are separated from the engine
    call dein#add('honza/vim-snippets')
    " Track the engine   
    call dein#add('SirVer/ultisnips')
else
    call dein#add('Shougo/unite.vim')
endif

if v:versionlong >= 9010646
    call dein#add('girishji/vimcomplete')
else 
    call dein#add('skywind3000/vim-auto-popmenu')
endif

if has('python3')
    call dein#add('puremourning/vimspector')
endif
call dein#add('skywind3000/asyncrun.vim')
call dein#add('lervag/vimtex')
call dein#add('chrisbra/csv.vim')

call dein#add('sbdchd/neoformat')

call dein#add('tpope/vim-fugitive')
call dein#add('mhinz/vim-signify')

call dein#add('voldikss/vim-floaterm')

call dein#add('junegunn/vim-easy-align')
call dein#add('mhinz/vim-startify')
call dein#add('wellle/context.vim')
call dein#add('luochen1990/rainbow')
call dein#add('psliwka/vim-smoothie')
call dein#add('itchyny/lightline.vim')
call dein#add('liuchengxu/vim-which-key')
call dein#add('rafi/awesome-vim-colorschemes')

" Finish dein initialization (required)
call dein#end()

call navigator#Config()
call lint#Config()
call completer#Config()
call runner#Config()
call vcs#Config()
call view#Config()

" View {{{1
try
    " Colorscheme may use plugin: gruvbox
    "colorscheme habamax
    colorscheme iceberg
catch
    " Builtin colorschemes: desert, peachpuff, quiet, slate
    colorscheme desert
endtry
" }}}1

" Options {{{1
set hlsearch    " Highlight the search results
set incsearch   " Show the pattern while typing

set modeline    " Modeline is the last comment line if vim is the editor. Use `help modeline` for detail.

set hidden  " Hide unsaved buffer

set expandtab   " Expand tag to space
set tabstop=4   " One tab includes four spaces
set shiftwidth=4    " The width of '<' and '>'
set backspace=indent,eol,start  " Allow backspacing over everything in insert mode.

set smartindent     " Do smart autoindenting

set ruler           " show the cursor position 
set wildmenu        " display completion matches in a status line
set number          " Show line number
set splitbelow      " New buffer splits below by default
set splitright      " New buffer splits right by default
set mouse=a         " Enable mouse in all mode
set scrolloff=5     " Show a few lines around the cursor
set fileencodings=utf-8,gb18030,latin1
set background=dark

if has('gui_running')
    " GUI options
    set guioptions=aegrLt
endif

syntax enable       " This enables Vim's syntax-related features. 
" Without this, some VimTeX features will not work 
" }}}1

" Commends {{{1

augroup CVimStart
    au!

    " A more suitable help file
    autocmd BufWinEnter * 
                \ if &filetype == 'help'
                \ |   set number 
                \ |   if winwidth('%') > 180
                \ |       wincmd L 
                \ |       vertical resize 90
                \ |   endif
                \ | endif

augroup END

" }}}1

" vim: set sw=4 sts=4 et:
